version: '3'
services:
  app:
    build: .
    volumes:
      - app-data:/app/dist
  http-server:
    depends_on:
      - app
    image: nginx:alpine
    environment:
      - VIRTUAL_HOST=cyntler.com,www.cyntler.com
    expose:
      - 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - app-data:/usr/share/nginx/html
volumes:
  app-data:
networks:
  default:
    name: nginx-proxy
