name: Production Deployment

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: npm install

      - name: Check / Prettier
        run: npm run prettier

      - name: Check / TypeScript typings
        run: npm run check-types

      - name: Check / Lint
        run: npm run lint

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Copy files to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: '.'
          target: '/var/personal-frontend'

      - name: Build the application and run by Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /var/personal-frontend
            docker build --no-cache -t personal-frontend .
            docker stop personal-frontend
            docker rm personal-frontend
            docker create --name personal-frontend -it personal-frontend
            docker cp /etc/letsencrypt/live/cyntler.com personal-frontend:/etc/letsencrypt/live/cyntler.com
            docker run -p 80:80 personal-frontend
